parameters:
  platform: ''

steps:
- powershell: |
    Get-ChildItem $(Build.SourcesDirectory)/ARMHelper
    Install-Module -Name Pester -Force -Scope CurrentUser -SkipPublisherCheck
    Install-Module -Name PSScriptAnalyzer -Force -Scope CurrentUser
    Import-Module "$(Build.SourcesDirectory)/ARMHelper" -Force
  displayName: 'Install Pester and import module'
- powershell: |
    $outputFile = ".\TEST-RESULTS.xml"
    Invoke-Pester -Tag Mock, Module -OutputFile $outputFile -OutputFormat NUnitXml -enableExit
  failOnStderr: false
  continueOnError: true
  displayName: 'Invoke-Pester without Azure'
- task: PublishTestResults@2
  displayName: 'Publish Offline Test Results'
  inputs:
    testRunTitle: "Offline Pester Results ${{ parameters.platform }}"
    buildPlatform: ${{ parameters.platform }}
    testRunner: 'NUnit'
    testResultsFiles: './TEST-RESULTS.xml'
    failTaskOnFailedTests: true

