name: Production
trigger:
  branches:
    include:
    - 'master'


pr:
- master

stages:
- stage: Build
  jobs:
  - job: BuildWindows
    pool:
      vmImage: windows-2019
    steps:
    - template: azure-pipelinestemplate.yml
      parameters:
        platform: 'Windows'
    - template: azure-pipelinesazuretemplate.yml
  - job: BuildMacOS
    pool:
      vmImage: macOS-10.14
    steps:
    - template: azure-pipelinestemplate.yml
      parameters:
        platform: 'MacOS'
  - job: BuildLinux
    pool:
      vmImage: ubuntu-16.04
    steps:
    - template: azure-pipelinestemplate.yml
      parameters:
        platform: 'Linux'

- stage: Deploy
  condition:
    and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  jobs:
  - job: DeploytoGallery
    pool:
      vmImage: windows-2019
      steps:
      - powershell: |
          Publish-Module -Path "$(Build.SourcesDirectory)/ARMHelper" -NuGetApiKey "$(GalleryApiKey)"
        displayName: 'Deploy to Gallery'
