name: Development

trigger:
  branches:
    include:
    - '*'  # must quote since "*" is a YAML reserved character; we want a string

stages:

- stage: Build
  jobs:
  - job: BuildWindows
    pool:
      vmImage: windows-2019
    steps:
    - template: azure-pipelinestemplate.yml
      parameters:
        platform: 'Windows'
    - task: AzurePowerShell@3
      displayName: 'Pester testing with Azure'
      inputs:
        azureSubscription: AzureConnection
        ScriptType: InlineScript
        Inline: |
          $outputFile = "$(Build.SourcesDirectory)\TEST-RESULTS.xml"
          Invoke-Pester -Script @{
          Path =  '$(Build.SourcesDirectory)\Tests\AzureTesting\pipelinetest.ps1'
          Parameters = @{
          TemplatePath = '$(Build.SourcesDirectory)\Tests\AzureTesting'
          }
          } -OutputFile $outputFile -OutputFormat NUnitXml -enableExit
      FailOnStandardError: false
      azurePowerShellVersion: LatestVersion
    - task: PublishTestResults@2
      displayName: 'Publish Offline Test Results'
      inputs:
        testRunTitle: 'online Pester Results $(platform)'
        buildPlatform: 'Windows'
        testRunner: 'NUnit'
        testResultsFiles: './TEST-RESULTS.xml'
      failTaskOnFailedTests: true
  - job: BuildMacOS
    pool:
      vmImage: macOS-10.14
    steps:
    - template: azure-pipelinestemplate.yml
      parameters:
        platform: 'MacOS'
  - job: BuildLinux
    pool:
      vmImage: ubuntu-16.04
    steps:
    - template: azure-pipelinestemplate.yml
      parameters:
        platform: 'Linux'
