name: Development

trigger:
  branches:
    include:
    - '*'  # must quote since "*" is a YAML reserved character; we want a string

stages:

- stage: Build
  jobs:
  - job: BuildWindows
    pool:
      vmImage: windows-2019
    steps:
    - template: azure-pipelinestemplate.yml
      parameters:
        platform: 'Windows'
  - job: BuildMacOS
    pool:
      vmImage: macOS-10.14
    steps:
    - template: azure-pipelinestemplate.yml
      parameters:
        platform: 'MacOS'
  - job: BuildLinux
    pool:
      vmImage: ubuntu-16.04
    steps:
    - template: azure-pipelinestemplate.yml
      parameters:
        platform: 'Linux'
